#: import SlideTransition kivy.uix.screenmanager.SlideTransition
#: import NoTransition kivy.uix.screenmanager.NoTransition
#: import Loader kivy.loader
#: import Text kivy.uix.textinput.TextInput
#: import RoundedRectangle kivy.graphics.vertex_instructions.RoundedRectangle
#: import NavigationDrawer kivy.garden.navigationdrawer

MyScreenManager:
    transition: SlideTransition()
    On_Hold_Screen:
    General_Info_Screen:
    In_Use_Screen:
    Log_in_Screen:

<Log_in_Screen>:
    name: 'log_in'
    #set names to displays so that text can be changed in the .py file
    emaildisplay: email
    passdisplay: password
    # Set background to white
    canvas:
        Color:
            rgba: 255, 255, 255, 1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: 'vertical'
        FloatLayout:
            #Background color label
            Label:
                canvas:
                    Color:
                        rgba: 0,0,255,0.1
                    Rectangle:
                        pos: self.pos
                        size: self.size

            #Make box around login
            Label:
                size_hint: (0.7, 0.8)
                pos_hint: {'center_y': 0.5, 'center_x': 0.5 }
                canvas:
                    Color:
                        rgba: 255, 255, 255, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
            # Set icon to login screen
            Image:
                size_hint: (0.2, 0.2)
                pos_hint: {'center_y': 0.7, 'center_x': 0.5 }
                source: root.icon_source

            TextInput:
                id: email
                bold: True
                size_hint: (0.6, 0.10)
                pos_hint: {'center_y': 0.45, 'center_x': 0.5 }
                hint_text: "[b]Email[/b]"
                multiline:False
                font_size: 18
            TextInput:
                id: password
                size_hint: (0.6, 0.10)
                pos_hint: {'center_y': 0.33, 'center_x': 0.5 }
                hint_text: 'Password'
                password: True
                multiline:False
                font_size: 18
            Button:
                text: 'Login'
                size_hint: (0.2, 0.10)
                pos_hint: {'center_y': 0.18, 'center_x': 0.5 }
                on_release:
                    root.login_check(email.text, password.text)
            Button:
                size_hint: (None, None)
                size: (80, 80)
                pos_hint: {'center_y': 0.9, 'center_x': 0.07 }
                background_normal:
                    root.backspace_source

                on_release:
                    app.root.transition = SlideTransition(direction='right')
                    app.root.current = 'gen_info'

<On_Hold_Screen>:
    name: 'hold'
    BoxLayout:
        Button:
            background_color: [0, 0, 0, 1]
            font_size: 80
            on_release: root.wake_up()

<General_Info_Screen>:
    name: 'gen_info'
    Image:
        id: 'image'
        size_hint: 1, 1
        pos: 0, root.y
        source: str(root.image_source)
    FloatLayout:
        id: 'float'
        Button:
            background_color: 0, 128, 128, .4
            size_hint: (.2, .15)
            pos_hint: {'top': .2, 'right': .75 }
            text: root.button1_text
            font_size: 20
            on_release:
                root.update_down()
        Button:
            background_color: 0, 128, 128, .4
            size_hint: (.2, .15)
            pos_hint: {'top': .2, 'right': .95 }
            text: root.button2_text
            font_size: 20
            on_release: root.update_up()
<In_Use_Screen>:
    name: 'in_use'
    NavDrawer:
<NavDrawer>:
    id: navdrawer
    anim_type: 'slide_above_anim'
    SidePanel:
        orientation: 'vertical'
        Label:
            size: (1, .4)
            text: 'Name'
        Button:
            text: 'One'
            on_touch_down: app.root.current = 'hold'
        Button:
            text: 'Two'
            on_touch_down: app.root.open()
        Button:
            text: 'Three'
        Button:
            text: 'Four'
    MainPanel
<MainPanel>:
    StackLayout:
        MenuBar:
        AsyncImage:
            size_hint: 1, 1
            pos: 0, root.y
            source: 'https://scontent.fhel1-1.fna.fbcdn.net/v/t1.0-9/18581920_10209336925155440_4663164082887279042_n.jpg?oh=ebd2dd333fdab1e4af06b594f5b4fc5e&oe=59B5CAA2'
<MenuBar>:
    pos_hint: {'top':1}
    background_color: 0, 128, 128, .4
    #Set labes and parameters
    ActionView:
        use_separator: True
        spacing: 30
        padding: (0, 0, 30, 0)
        ActionMenu:
            title: ''
            with_previous: False
            app_icon: 'images/icons/menu_icon.png'
            on_release:
                app.root.navdrawer.toggle_state()
        ActionLabel:
            text: 'Name'
            font_size: 25
        ActionLabel:
            text: 'Time'
            font_size: 25
        ActionLabel:
            text: 'Date'
            font_size: 25
